admin node search exclusions:
  title: 'Exclude nodes from search results'
  description: 'This allows users with this permission to flag content as not to be searched.'

search all content:
  title: 'Search all content types'
  description: 'Allow users to search any content, overriding content type permissions.'

search all excluded entities:
  title: 'Search excluded content'
  description: 'Allow users to search any content, overriding individual content item exclusion settings.'

permission_callbacks:
  - \Drupal\search_config\searchConfigPermissions::searchConfigPermissions
