<?php
/**
 * @file
 * Contains formularios.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function formularios_sisec_theme($existing, $type, $theme, $path) {
  return [
    'examen-licencia' => [
      'template' => 'examen-licencia',
      'variables' => [
        'items' => NULL
      ],
    ],
    'compra-pin' => [
      'template' => 'compra-pin',
      'variables' => [
        'items' => NULL
      ],
    ],
    'examen-licencia-resumen' => [
      'template' => 'examen-licencia-resumen',
      'variables' => [
        'items' => NULL
      ],
    ],
    'examen-licencia-confirmacion' => [
      'template' => 'examen-licencia-confirmacion',
      'variables' => [
        'items' => NULL
      ],
    ],
    'examen-licencia-anulacion' => [
      'template' => 'examen-licencia-anulacion',
      'variables' => [
        'items' => NULL
      ],
    ],
  ];
}

