<?php
/**
 * @file
 * Contains formularios.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\ConfigFormBase;

/**
 * Theme hook
 */
function blocks_custom_theme($existing, $type, $theme, $path)
{
    return [
        'blocks_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'publicaciones' => NULL
                ],
                'template' => 'publications'
            ],
        'news_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'news' => NULL
                ],
                'template' => 'news'
            ],
        'filters_publications_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'year' => NULL,
                    'month' => NULL
                ],
                'template' => 'filters-publications'
            ],
        'categories_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'terms' => NULL,
                    'title' => NULL
                ],
                'template' => 'categories'
            ],
        'recent_publications_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'recents' => NULL,
                    'nid' => NULL
                ],
                'template' => 'recent-publications'
            ],
        'title_categories_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'title' => NULL
                ],
                'template' => 'title-publications'
            ],
        'reports_prime_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'reports' => NULL
                ],
                'template' => 'reports-prime'
            ],
        'paginator_reports_prime_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'reports' => NULL
                ],
                'template' => 'paginator-reports-prime'
            ],
        'menu_login_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'user' => NULL
                ],
                'template' => 'menu-prime'
            ],
        'interest_blocks_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'interests' => NULL
                ],
                'template' => 'interest-block'
            ],
        'participant_blocks_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'participants' => NULL
                ],
                'template' => 'participants'
            ],
        'list_documents_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'recents' => NULL
                ],
                'template' => 'list-documents'
            ],
        'registered_participants_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Participantes Registrados',
                    'descripcion' => 'Participantes Registrados',
                    'title' => NULL
                ],
                'template' => 'registered-participants'
            ],
        'archivo_informe_prime_igas_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Archivo Informe Prime IGas',
                    'descripcion' => 'Lista de archivos del informe prime IGas',
                    'archivos' => NULL
                ],
                'template' => 'archivo-informe-prime-igas'
            ],
        'archivo_informe_diario_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Archivo Informe Diario',
                    'descripcion' => 'Lista de archivos informes diarios',
                    'archivos' => NULL
                ],
                'template' => 'archivo-informe-diario'
            ],
        'power_bi_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Tablas Power BI',
                    'descripcion' => 'Tablas Power BI',
                    'reports' => NULL
                ],
                'template' => 'power-bi'
            ]
    ];
}

/*
*
*  hook_form_alter implement
*/
function blocks_custom_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    $pass = '';
    $legal = '';
    if ($form_id == 'user_register_form') {
        $register = '<a href="/user/login/" title="Inicio Sesión en Prime"
                class="btn secondary_colour_3-text primary_colour_1-bk">
                <span>Ya estoy inscrito. Iniciar Sesión</span>
                </a>';
        $text = '<p style="text-align: justify;">Regístrese&nbsp; en la&nbsp;<em><strong>Versión Prime</strong></em> y&nbsp;tenga acceso a información exclusiva sobre el <strong>Mercado de Gas Natural en Colombia</strong>.<br><br></p>';
        $titleForm = 'Diligencie la siguiente información:';
        $legal = '<div class="modal-content-">
      <div class="modal-header">
        
       <h3 class="color-text-blue">Aviso de privacidad y protección de datos personales</h3>
      </div>
      <div class="modal-body" style="text-align: justify;">
      <p>La BMC BOLSA MERCANTIL DE COLOMBIA S.A identificado con NIT 860.071.250-9 ubicada en la Calle 113 # 7 – 21 Teleport Business Park torre A - piso 15 de la ciudad de Bogotá será el responsable del tratamiento y, en tal virtud, podrá recolectar, almacenar y usar su información personal para:</p>
<p>
a. Acceder a los servicios del Gestor del Mercado de Gas previstos en el artículo 6 de la Resolución CREG 114 de 2017.
b. Adelantar campañas de actualización de noticias, eventos y/o capacitaciones que realice la Bolsa Mercantil de Colombia, en su condición de Gestor del Mercado de Gas.
c. Enviar Boletines informativos sobre el comportamiento del mercado.
d. Cumplir con requisitos y/o requerimientos de autoridades administrativas sectoriales y/o judiciales.
e. Cumplir con los requisitos legales para el debido conocimiento del cliente, cuando sea el caso.
f. Adelantar campañas de actualización de datos e información de cambios en el tratamiento de datos personales.
g. Adelantar comunicaciones o contacto vía correo electrónico, SMS, teléfono u otro medio.
</p>
<p>
Así mismo, se le informa que como titular de sus datos personales usted tiene derecho a: 
</p>
<p>
(i) Acceder en forma gratuita a los datos proporcionados que hayan sido objeto de tratamiento.
(ii) Conocer, actualizar y rectificar su información frente a datos parciales, inexactos, incompletos, fraccionados, que induzcan a error, o a aquellos cuyo tratamiento esté prohibido o no haya sido autorizado.
(iii) Solicitar prueba de la autorización otorgada.
(iv) Presentar ante la Superintendencia de Industria y Comercio (SIC) quejas por infracciones a lo dispuesto en la normatividad vigente. Revocar la autorización y/o solicitar la supresión del dato, siempre que no exista un deber legal o contractual que impida eliminarlos.
(v) Abstenerse de responder las preguntas sobre datos sensibles.
</p>
<p>
Si desea no autorizar alguna finalidad puede presentar una solicitud escribiendo al correo electrónico servicioalcliente@bolsamercantil.com.co o a través de cualquiera de los canales que BMC BOLSA MERCANTIL DE COLOMBIA S.A ha habilitado para tal fin. Tenga en cuenta que dicha solicitud requerirá cumplir lo descrito en el artículo 2.2.2.25.4.1 del Decreto 1074 de 2015 y el numeral 3.3.1 de la política de protección de datos de BMC BOLSA MERCANTIL DE COLOMBIA S.A la cual se encuentra publicada en www.bolsamercantil.com.co
</p>
<p>
 El marcar esta casilla y diligenciar el presente formulario se entenderá como una conducta concluyente de que otorga su consentimiento de forma libre y voluntaria a BMC BOLSA MERCANTIL DE COLOMBIA S.A para que trate su información personal de acuerdo con las finalidades descritas anteriormente.
</p>
<p>
					<input id="ChkAvisocheckid" type="checkbox" class="ChkAvisocheck" name="ChkAvisocheckid">	
					<span style="display: none;"><input class="text-box single-line" id="registerModel_MemberProperties_3__Value" name="registerModel.MemberProperties[3].Value" type="text" value=""></span>
<input id="registerModel_MemberProperties_3__Alias" name="registerModel.MemberProperties[3].Alias" type="hidden" value="privacyNotice"><label for="ChkAvisocheckid">El marcar esta casilla y diligenciar el presente formulario se entenderá como una conducta concluyente de que otorga su consentimiento de forma libre y voluntaria a BMC BOLSA MERCANTIL DE COLOMBIA S.A para que trate su información personal de acuerdo con las finalidades descritas anteriormente.</label>
</p>
      </div>
    </div>';
    }
    if ($form_id == 'user_login_form') {
        $pass = '<br><a href="/user/password">¿Olvido su contraseña?</a>';
        $register = '<a href="/user/register/" title="Registro a Prime"
                   class="btn secondary_colour_3-text primary_colour_1-bk">
                    <span>Aún no estoy inscrito, registrarme</span>
                </a>';
        $text = '<p style="text-align: justify;">Si ya está registrado, ingrese al&nbsp;<em><strong>Acceso
                        Prime</strong></em>&nbsp;con su correo electrónico (usuario)&nbsp;y contraseña, enviados
                porterior al Congreso Naturgas 2018</p>
            <p>&nbsp;</p>';
        $titleForm = 'Ingrese los Datos de Acceso a la Sección Prime:';
    }

    $prefix = '<div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="heading">Acceso Prime</h1>
            </div>
        </div>
        <div class="row">
        <div id="left_col" class="col-sm-8" role="main">
            <p class="img-login-content" style="text-align: center;"></p>
            <p>&nbsp;</p>
            <p class="content-btn-register">
                ' . $register . '
            </p>
            <p>&nbsp;</p>
            ' . $text . '
            <div class="login-user-bk"><span class="legend-user-login">' . $titleForm . '</span>';
    $suffix = $pass . ' </div></div>
        <div id="right_col" class="col-sm-4 col-lg-3 col-lg-offset-1" role="complementary">
                <div class="promo_pods ">
                    <div class="item panel panel-default even">
                        <div class="panel-body primary_colour_1-bg">
                            <a href="/sitios-de-interés/"><p class="heading secondary_colour_3-text">Sitios de Interés </p></a>
                            <div class="info">
                                <div class="text secondary_colour_3-text"><p>Conozca&nbsp;todas las entidades que hacen parte del sector del Gas Natural&nbsp;en Colombia.</p>
                                </div>
                                <p class="link"><a href="/sitios-de-interés/" class="btn primary_colour_2-bg secondary_colour_3-text">Ver todos</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item panel panel-default odd">
                        <div class="panel-body primary_colour_2-bg">
                            <p class="heading secondary_colour_3-text">Nuestras Oficinas </p>
                            <div class="info">
                                <div class="text secondary_colour_3-text">
                                    <p>Calle 113 No. 7-21<br>Piso 15 Torre A
                                        <br>Edif.&nbsp;Teleport Business Park
                                        <br>Pbx: +57(1) 629-2529
                                        <br>Bogotá D.C., Colombia
                                    </p>
                                </div>
                                <p class="link"><a href="/contáctenos/#pos_1327" class="btn secondary_colour_3-bg primary_colour_1-text">Escríbanos sus comentarios</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div></div><br><br><br><div id="ex1" class="modal">' . $legal . '</div>';

    if ($form_id == 'user_login_form') {
        $form['#prefix'] = $prefix;
        $form['name']['#title'] = 'Correo Electrónico (será su usuario) ';
        $form['pass']['#title'] = 'Contraseña';
        $form['#suffix'] = $suffix;
    }

    if ($form_id == 'user_register_form') {
        $form['#prefix'] = $prefix;
        $form['account']['mail']['#title'] = 'Correo Electrónico (será su usuario)';
        $form['legal']['conditions']['#title'] = 'Consulte y valide el Aviso de privacidad y protección de datos personales haciendo <a href="/legal">CLICK AQUÍ.</a>';
        // $form['account']['legal_accept']['#title'] =  'Consulte y valide el Aviso de privacidad y protección de datos personales haciendo';
        $form['actions']['submit']['#value'] = 'Registrarme';
        $form['#suffix'] = $suffix;
    }

    if ($form_id == 'user_pass') {
        $form['#prefix'] = $prefix;
        $form['name']['#title'] = 'Correo Electrónico (será su usuario) ';
        $form['actions']['submit']['#value'] = 'Recuperar';
        $form['#suffix'] = $suffix;
    }
}
