<?php
/**
 * @file
 * Contains formularios.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\ConfigFormBase;

/**
 * Theme hook
 */
function blocks_custom_theme($existing, $type, $theme, $path)
{
    return [
        'blocks_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'publicaciones' => NULL
                ],
                'template' => 'publications'
            ],
        'news_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'news' => NULL
                ],
                'template' => 'news'
            ],
        'filters_publications_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'year' => NULL,
                    'month' => NULL
                ],
                'template' => 'filters-publications'
            ],
        'categories_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'terms' => NULL,
                    'title' => NULL
                ],
                'template' => 'categories'
            ],
        'recent_publications_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'recents' => NULL,
                    'nid' => NULL
                ],
                'template' => 'recent-publications'
            ],
        'title_categories_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'title' => NULL
                ],
                'template' => 'title-publications'
            ],
        'reports_prime_block_custom' =>
            [
                'variables' => [
                    'titulo' => 'Título por defecto',
                    'descripcion' => 'descripción por defecto',
                    'reports' => NULL
                ],
                'template' => 'reports-prime'
            ]
    ];
}

/*
*
*  hook_form_alter implement
*/
function blocks_custom_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    global $base_url;
    $prefix = '
        <div id="left_col" class="col-sm-8" role="main">
            <p class="img-login-content" style="text-align: center;"></p>
            <p>&nbsp;</p>
            <p class="content-btn-register">
                <a href="/user/register/" title="Registro a Prime"
                   class="btn secondary_colour_3-text primary_colour_1-bk">
                    <span>Aún no estoy inscrito, registrarme</span>
                </a>
            </p>
            <p>&nbsp;</p>
            <p style="text-align: justify;">Si ya está registrado, ingrese al&nbsp;<em><strong>Acceso
                        Prime</strong></em>&nbsp;con su correo electrónico (usuario)&nbsp;y contraseña, enviados
                porterior al Congreso Naturgas 2018</p>
            <p>&nbsp;</p>
            <div class="login-user-bk"><span class="legend-user-login">Ingrese los Datos de Acceso a la Sección Prime:</span>';
    $suffix = '<br><a href="/user/password">¿Olvido su contraseña?</a></div></div>';
    $myConfig = \Drupal::config('fancy_login.settings');
    $site_name = \Drupal::config('system.site')->get('name');
    if ($form_id == 'user_login_form') {
        $form['#prefix'] = $prefix;
        $form['name']['#title'] = 'Correo Electrónico (será su usuario) ';
        // $form['name']['#description'] = !empty($myConfig->get('username_description')) ? $myConfig->get('username_description') : t('Enter your @s username.', array('@s' =>$site_name));
        $form['pass']['#title'] = 'Contraseña';
        // $form['pass']['#description'] = !empty($myConfig->get('password_description')) ? $myConfig->get('password_description') : '';
        $form['#suffix'] = $suffix;
    }

    if ($form_id == 'user_register_form') {
        $form['#prefix'] = $prefix;
        $form['name']['#title'] = !empty($myConfig->get('forgot_form_username')) ? $myConfig->get('forgot_form_username') : 'Username';
        $form['#suffix'] = $suffix;
    }
    if ($form_id == 'user_register_form') {
        $form['account']['mail']['#description'] = !empty($myConfig->get('register_mail_desc')) ? $myConfig->get('register_mail_desc') : '';
        $form['account']['mail']['#title'] = !empty($myConfig->get('register_form_mail')) ? $myConfig->get('register_form_mail') : 'Email Address.';
        $form['account']['name']['#description'] = !empty($myConfig->get('register_mail_desc')) ? $myConfig->get('register_mail_desc') : "";
        $form['account']['name']['#title'] = !empty($myConfig->get('register_form_name')) ? $myConfig->get('register_form_name') : 'Username';
        $form['actions']['submit']['#value'] = !empty($myConfig->get('register_form_button')) ? $myConfig->get('register_form_button') : 'Create new account.';
    }
}
